/*==============================================================================
  DFA Distributional Financial Accounts — Balance Sheet Breakdowns & Checks
  Source: Federal Reserve DFA (dfa-networth-levels-detail.csv)
  All monetary variables in millions of dollars.
  Variable names are those auto-generated by Stata from the CSV header row.
==============================================================================*/


// Set Globals and Locals
********************************************************************************

clear all

local source FED_DWA_ineq

global ineq_dir_raw raw_data/ineq

	local sourcef "${ineq_dir_raw}/`source'"
	
	local rawdata "`sourcef'/raw data/dfa-networth-levels-detail.csv"
	
	local results "`sourcef'/final_table/`source'"
	
	
// Load Data	
********************************************************************************
import delimited "`rawdata'" ,  clear 
** Assets: unit Millions of Dollars
** householdcount : units

// Keep only Q4
****************************************
split date, p(:)
drop date
rename date1 year
destring year, replace
rename date2 quarter
keep if quarter=="Q4"
drop quarter
order year 


// Code Variabels
****************************************
gen percentile=""
replace percentile="p99_9p100" if category=="TopPt1"
replace percentile="p99p99_9" if category=="RemainingTop1"
replace percentile="p90p99" if category=="Next9"
replace percentile="p50p90" if category=="Next40"
replace percentile="p0p50" if category=="Bottom50"



// Assets Classes according to topography
****************************************


*------------------------------------------------------------------------------
* Breakdown Net Wealth;
*******************************************************************************
*    nonfinancialassets                   = Nonfinancial assets
*    	realestate                           = Real estate
*   	consumerdurables                     = Consumer durables
*    financialassets                      = Financial assets
*    	deposits                             = Deposits
*    	moneymarketfundshares                = Money market fund shares
*    	debtsecurities                       = Debt securities
*    		usgovernmentandmunicipalsecuriti     = U.S. government and municipal securities
*    		corporateandforeignbonds             = Corporate and foreign bonds
*    	loansassets                          = Loans (Assets)
*    		otherloansandadvancesassets          = Other loans and advances (Assets)
*    		mortgages                            = Mortgages
*    	corporateequitiesandmutualfundsh     = Corporate equities and mutual fund shares
*    	lifeinsurancereserves                = Life insurance reserves
*    	annuities                            = Annuities
*    	dcpensionentitlements                = DC pension entitlements
*    	dbpensionentitlements                = DB pension entitlements
*    	miscellaneousotherequity             = Miscellaneous other equity
*    	miscellaneousassets                  = Miscellaneous assets
*    liabilities                          = Liabilities
*    	loansliabilities                     = Loans (Liabilities)
*    		homemortgages                        = Home mortgages
*    		consumercredit                       = Consumer credit
*    		depositoryinstitutionsloansnec       = Depository institutions loans n.e.c.
*    		otherloansandadvancesliabilities     = Other loans and advances (Liabilities)
*    	deferredandunpaidlifeinsurancepr     = Deferred and unpaid life insurance premiums
*------------------------------------------------------------------------------
** Checks /*
	gen check=nonfinancialassets-(realestate+consumerdurables)
	sum check
	drop check
	
	gen check=financialassets-(deposits+moneymarketfundshares+debtsecurities+ ///
			loansassets+corporateequitiesandmutualfundsh+lifeinsurancereserves+	///
			annuities+dcpensionentitlements+dbpensionentitlements+miscellaneousotherequity+ ///
			miscellaneousassets)
	sum check 
	drop check
	
	gen check=loansassets-(otherloansandadvancesassets+mortgages)
	sum check 
	drop check
	

	
	
	gen check=liabilities-(loansliabilities+deferredandunpaidlifeinsurancepr)
	sum check
	drop check
*/


********************************************************************************
** Assing These Asset and Laiab to Topography aggregates
********************************************************************************

gen nfahou=realestate
gen nfadur=consumerdurables
egen facdbl=rowtotal(deposits	///
					moneymarketfundshares	///
					usgovernmentandmunicipalsecuriti	///
					corporateandforeignbonds	///
					otherloansandadvancesassets	///
					mortgages)
egen faeqfd=rowtotal(	moneymarketfundshares		///
						corporateequitiesandmutualfundsh)
egen falipe=rowtotal(lifeinsurancereserves	///
					annuities	///
					dcpensionentitlements	///
					dbpensionentitlements	)
egen fliabi=rowtotal(homemortgages		///
			consumercredit		///
			depositoryinstitutionsloansnec		///
			otherloansandadvancesliabilities		///
			deferredandunpaidlifeinsurancepr)
replace fliabi=-fliabi

gen nnhass=financialassets
			
gen other=miscellaneousotherequity+miscellaneousassets

gen netwea=networth			
			
			
			
			
// Loop Over Assets
****************************************
tempfile XXX
save `XXX' , replace

foreach var in netwea nfahou nfadur nnhass fliabi {

clear

use `XXX'

rename `var' value
rename householdcount population

gen varcode="t-hs-XXX-`var'-ho"
gen area="US"
gen source="`source'"

keep area year value percentile varcode source population





// All Totals -- useful for Distributional Topo (Dataset 2)
********************************************************************************
preserve
	drop population
	replace varcode="t-hs-tot-`var'-ho"
	
	reshape wide value, i(area year varcode source) j(percentile) string

	
	// Aggregates
	gen valuep0p100=		(valuep0p50			+ 	valuep50p90 		+	valuep90p99 		+	valuep99p99_9		+ valuep99_9p100)
	
	// Expand
	// Aggregates
	gen valuep0p90    = valuep0p50 + valuep50p90                                                   // Bottom 90
	gen valuep90p100  = valuep90p99 + valuep99p99_9 + valuep99_9p100                              // Top 10
	gen valuep99p100  = valuep99p99_9 + valuep99_9p100                                            // Top 1
	
	reshape long value , i(area year varcode source) j(percentile) string
	
	
	replace percentile="p99.9p100" 	if percentile=="p99_9p100" 
	replace percentile="p99p99.9"  	if percentile=="p99p99_9" 
	*drop if percentile=="p99p99.9"
	
	** Million Dollars
	replace value= value * 1000000
	
	tempfile tot
	save `tot', replace
restore

	
	
	
// Calulate Averages
********************************************************************************
preserve	
	replace varcode="t-hs-avg-`var'-ho"
	
	reshape wide value population, i(area year varcode source) j(percentile) string

	
	// Aggregates
	foreach x in value population {
		gen `x'p0p100=		(`x'p0p50			+ 	`x'p50p90 		+	`x'p90p99 		+	`x'p99p99_9		+ `x'p99_9p100)
		
		// Expand
		// Aggregates
		gen `x'p0p90    = `x'p0p50 + `x'p50p90                                                   // Bottom 90
		gen `x'p90p100  = `x'p90p99 + `x'p99p99_9 + `x'p99_9p100                              // Top 10
		gen `x'p99p100  = `x'p99p99_9 + `x'p99_9p100                                            // Top 1
	}
	
	
	// Averages
	foreach p in p0p100 p0p50 p0p90 p50p90 p90p100 p90p99 p99p100 p99p99_9 p99_9p100 {
		gen xvalue`p'=value`p'/population`p'
	}
	
	drop value* population*
	
	reshape long xvalue , i(area year varcode source) j(percentile) string
	
	rename xvalue value
	
	replace percentile="p99.9p100" 	if percentile=="p99_9p100" 
	replace percentile="p99p99.9"  	if percentile=="p99p99_9" 
	*drop if percentile=="p99p99.9"
	
	** Million Dollars
	replace value= value * 1000000
	
	tempfile avg
	save `avg', replace
restore
	

	

// Calulacate Shares
********************************************************************************
if "`var'"=="netwea" {
preserve
	replace varcode="t-hs-dsh-`var'-ho"
	
	drop population
	reshape wide value , i(area year varcode source) j(percentile) string

	
	// Aggregates
	foreach x in value  {
		gen `x'p0p100=		(`x'p0p50			+ 	`x'p50p90 		+	`x'p90p99 		+	`x'p99p99_9		+ `x'p99_9p100)
		
		// Expand
		// Aggregates
		gen `x'p0p90    = `x'p0p50 + `x'p50p90                                                 // Bottom 90
		gen `x'p90p100  = `x'p90p99 + `x'p99p99_9 + `x'p99_9p100                              // Top 10
		gen `x'p99p100  = `x'p99p99_9 + `x'p99_9p100                                          // Top 1
	}
	
	
	// Shares
	foreach p in p0p50 p0p90 p50p90 p90p100 p90p99 p99p100 p99p99_9 p99_9p100 {
		gen xvalue`p'=value`p'/valuep0p100
	}
	
	drop value*
	
	reshape long xvalue , i(area year varcode source) j(percentile) string
	
	rename xvalue value
	
	replace percentile="p99.9p100" 	if percentile=="p99_9p100" 
	replace percentile="p99p99.9"  	if percentile=="p99p99_9" 
	
	
	** Million Dollars
	replace value= value * 100

	tempfile dsh
	save `dsh', replace
restore
}

if "`var'"!="netwea" {
	clear	
	set obs 1
	gen year=.
	tempfile dsh
	save `dsh', replace
}


clear
use `tot'
append using `avg'
append using `dsh'

drop if year==.


** Avoid duplicates
bys area year varcode percentile: gen N=_n
tab N
drop N


tempfile a`var'
save `a`var'', replace

}

clear
foreach var in netwea nfahou nfadur nnhass fliabi {
	append using `a`var''
}

** Calulate Shares
********************************************************************************
preserve
	split varcode, p(-)
	keep if varcode3=="tot"
	bys year: gen help1=value if varcode=="t-hs-tot-netwea-ho" & percentile=="p0p100"
	bys year: egen help2=max(help1)
	replace value=(value/help2)*100
	drop help*
	replace varcode3="dsh"
	
	replace varcode=varcode1+"-"+varcode2+"-"+varcode3+"-"+varcode4+"-"+varcode5
	drop varcode1 varcode2 varcode3 varcode4 varcode5 
	
	tempfile dsh
	save `dsh', replace
restore

append using `dsh'

	
	/*
	// Check Distributional Topography
	preserve
		keep if area=="US"
		keep if year==2020
		list
		
		** Isolate Percentiles valid for Distrib Topo 
		foreach concept in nfahou nnhass fliabi nfadur {
			gen value_`concept'=value  if varcode=="t-hs-dsh-`concept'-ho"
		}
		
		
		// Display dshby by percentile
		graph bar value_* , stack over(percentile , label(angle(45)))	name(a, replace)
		
		// Disply dsh/weath share by percentile
		bys area year percentile: gen help=value if varcode=="t-hs-dsh-netwea-ho"  
		bys area year percentile: egen nwshare=max(help)
		
		foreach concept in nfahou nnhass fliabi nfadur {
			gen nwshare_`concept'=value/nwshare  if varcode=="t-hs-dsh-`concept'-ho"
		}
		
		graph bar nwshare_* , stack over(percentile , label(angle(45)))	name(b, replace)
		
		graph combine a b
	
	restore
	*/
	
** Check no duplicates	
bys area year percentile varcode: gen N=_n
tab N
drop if N>=2
drop N

	

	
//export
order area year value percentile varcode source
qui export delimited "`results'", replace 	

	
	




































