# Shared render configuration for warehouse documentation.
#
# This support file is the one place where render paths and document ordering
# are defined. render.R and the master document both source it, so a folder move
# or version update should not require edits in several files.

find_render_config_file <- function() {
  for (frame in rev(sys.frames())) {
    if (!is.null(frame$ofile) && basename(frame$ofile) == "render_config.R") {
      return(normalizePath(frame$ofile, mustWork = TRUE))
    }
  }

  support_path <- file.path("render_support", "render_config.R")
  if (file.exists(support_path)) {
    return(normalizePath(support_path, mustWork = TRUE))
  }

  if (file.exists("render_config.R")) {
    return(normalizePath("render_config.R", mustWork = TRUE))
  }

  stop("Could not locate render_config.R.", call. = FALSE)
}

render_config_file <- find_render_config_file()
render_config_dir <- dirname(render_config_file)
doc_root <- if (basename(render_config_dir) == "render_support") {
  dirname(render_config_dir)
} else {
  render_config_dir
}
doc_root <- normalizePath(doc_root, mustWork = TRUE)
sections_dir <- file.path(doc_root, "sections")
outputs_dir <- file.path(doc_root, "outputs")
# Standalone section renders go directly into outputs/. The source Rmd files
# stay in sections/, while generated PDFs stay in the generated-output folder.
section_outputs_dir <- outputs_dir

warehouse_version <- "2"

# The master Rmd is internal. Users render it through render.R, which writes the
# final PDF to the root folder as warehouse_documentation.pdf.
master_rmd_file <- "_master.Rmd"
master_rmd_path <- file.path(sections_dir, master_rmd_file)
master_output_file <- "warehouse_documentation.pdf"
master_output_path <- file.path(doc_root, master_output_file)

# These files are rendered as standalone preview choices, but in the menu they
# are shown after the topical sections and before appendices.
front_section_files <- c("author.Rmd", "proj.Rmd", "gral.Rmd")

# The master document order is intentionally explicit because it is editorial:
# changing this list changes the order of the compiled documentation. The paths
# themselves are generated by master_child_paths(), so the folder name is still
# centralized here instead of repeated in the master Rmd.
master_child_files <- c(
  "proj.Rmd",
  "gral.Rmd",
  "topo.Rmd",
  "ineq.Rmd",
  "taxw.Rmd",
  "inhe.Rmd",
  "a_apdx_supp.Rmd",
  "a_apdx_topo.Rmd",
  "a_apdx_ineq.Rmd",
  "a_apdx_taxw.Rmd",
  "a_apdx_inhe.Rmd"
)

# Nested children are fragments included by sections, not standalone menu
# choices. They are listed here so the preliminary checks can validate them.
fragment_files <- c("wt_balancesheet_new.Rmd", "wt_balancesheet_new_html.Rmd")

# Labels override the automatic filename-to-title conversion when a short or
# project-specific name is clearer than the file stem.
section_label_overrides <- c(
  "author.Rmd" = "Author",
  "proj.Rmd" = "Project Overview",
  "gral.Rmd" = "General Warehouse Structure",
  "topo.Rmd" = "Wealth Topography",
  "inhe.Rmd" = "Inheritance Trends",
  "ineq.Rmd" = "Wealth Inequality",
  "taxw.Rmd" = "Taxes on Wealth",
  "a_apdx_supp.Rmd" = "Appendix: Supplementary Variables",
  "a_apdx_topo.Rmd" = "Appendix: Wealth Topography",
  "a_apdx_inhe.Rmd" = "Appendix: Inheritance Trends",
  "a_apdx_ineq.Rmd" = "Appendix: Wealth Inequality",
  "a_apdx_taxw.Rmd" = "Appendix: Taxes on Wealth"
)

path_from_root <- function(...) {
  file.path(doc_root, ...)
}

render_path <- function(x, mustWork = FALSE) {
  normalized <- normalizePath(x, winslash = "/", mustWork = mustWork)
  gsub("\\", "/", normalized, fixed = TRUE)
}

master_child_paths <- function() {
  file.path(sections_dir, master_child_files)
}

required_child_files <- function() {
  c(
    file.path("sections", master_rmd_file),
    file.path("sections", "author.Rmd"),
    file.path("sections", master_child_files),
    file.path("sections", "fragments", fragment_files)
  )
}

label_from_section_file <- function(file) {
  override <- unname(section_label_overrides[file])
  if (!is.na(override)) {
    return(override)
  }

  name <- tools::file_path_sans_ext(file)
  is_appendix <- startsWith(name, "a_")
  name <- sub("^a_", "", name)
  name <- sub("^apdx_", "", name)
  label <- tools::toTitleCase(gsub("_", " ", name))
  if (is_appendix) {
    label <- paste("Appendix:", label)
  }
  label
}

ordered_section_files <- function() {
  # Preview choices are discovered automatically from sections/*.Rmd. New
  # topical sections appear before author/proj/gral; files beginning with a_
  # appear at the end as appendices.
  files <- list.files(sections_dir, pattern = "\\.Rmd$", full.names = FALSE)
  files <- files[!file.info(file.path(sections_dir, files))$isdir]
  files <- files[!startsWith(files, "_")]

  non_appendix <- files[!startsWith(files, "a_")]
  master_main <- master_child_files[
    master_child_files %in% non_appendix &
      !master_child_files %in% front_section_files
  ]
  discovered_main <- sort(setdiff(non_appendix, c(front_section_files, master_main)))
  main_sections <- c(master_main, discovered_main)
  front_sections <- front_section_files[front_section_files %in% files]
  appendix_files <- files[startsWith(files, "a_")]
  master_appendices <- master_child_files[master_child_files %in% appendix_files]
  discovered_appendices <- sort(setdiff(appendix_files, master_appendices))
  appendices <- c(master_appendices, discovered_appendices)

  c(main_sections, front_sections, appendices)
}

section_targets <- function() {
  files <- ordered_section_files()
  data.frame(
    index = seq_along(files),
    key = tools::file_path_sans_ext(files),
    label = vapply(files, label_from_section_file, character(1)),
    file = files,
    path = file.path(sections_dir, files),
    output_file = paste0(tools::file_path_sans_ext(files), ".pdf"),
    stringsAsFactors = FALSE
  )
}
